name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create required directories
        run: |
          mkdir -p static staticfiles media

      - name: Set up environment variables
        run: |
          echo "SECRET_KEY=test-secret-key-for-github-actions" >> $GITHUB_ENV
          echo "DEBUG=False" >> $GITHUB_ENV

      - name: Check Django configuration
        run: |
          python manage.py check

      - name: Run migrations
        run: |
          python manage.py migrate --run-syncdb

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Run tests with coverage
        run: |
          python manage.py test --keepdb --parallel

      - name: Clean up test database
        run: |
          rm -f db.sqlite3
